server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
      separator: ";"
